mission9_jacklin5/Controllers/PaymentController.cs
using Microsoft.AspNetCore.Mvc;
using mission9_jacklin5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission9_jacklin5.Controllers
{
    public class PaymentController : Controller
    {
        private IPaymentRepository repo { get; set; }
        private Cart cart { get; set; }     //This brings in the session, this is why we added session material to the cart.cs file

        public PaymentController(IPaymentRepository temp, Cart c)      //Constructor
        {
            repo = temp;
            cart = c;       
        }

        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Payment());     //Creates new payment object for me
        }

        [HttpPost]
        public IActionResult Checkout(Payment payment)      //Checks if our payment is valid or not
        {
            if(cart.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if(ModelState.IsValid)          //This means payment is not empty, it is zero
            {
                payment.cartItems = cart.Items.ToArray();       //Stores items for us
                repo.SavePayment(payment);      //Found in our EFPaymentRepository. If there is no PaymentId, it will add payment for us
                cart.ClearCart();
                return RedirectToPage("/PaymentConfirmation");
            }
            else
            {
                return View();          //If paymentid is not real, then it just takes us back
            }
        }
    }
}

mission9_jacklin5/Pages/PaymentConfirmation.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace mission9_jacklin5.Pages
{
    public class PaymentConfirmationModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

mission9_jacklin5/Pages/Shop.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using mission9_jacklin5.Infrastructure;
using mission9_jacklin5.Models;

namespace mission9_jacklin5.Pages
{
    public class ShopModel : PageModel                  //Model for our cart page
    {
        private IBookstoreRepository repo {get; set;}

        public ShopModel (IBookstoreRepository temp, Cart c)
        {
            repo = temp;
            cart = c;
        }
        public Cart cart { get; set; }
        public string ReturnUrl { get; set; }           //So we can direct users back to where they were browsing
        
        
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            
        }

        public IActionResult OnPost(int bookID, string returnUrl)       //When we want to access the cart page we need to know what book we want to purchase and where to go back to
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookID);        //Check if book is in our database


            cart.AddItem(b, 1);     //Calls the addItem function

            return RedirectToPage(new { ReturnUrl = returnUrl });   //Takes us back to where we were
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)     //Method for our form we created on shop.cshtml page
        {
            cart.RemoveItem(cart.Items.First(x => x.Book.BookId == bookId).Book);   //Finds the book in our list of books and returns the instance of Book that it belongs to

            return RedirectToPage(new { ReturnUrl = returnUrl });   //Takes us back to where we were
        }
    }
}

mission9_jacklin5/Pages/PaymentConfirmation.cshtml
@page
@model mission9_jacklin5.Pages.PaymentConfirmationModel
@{
}


<div class="text-center">
    <h2>Thanks! Your order is on its way!</h2>
    <a class="btn btn-danger" asp-controller="Home">Return Home</a>         @*Confirmation page for when we order a book*@
</div>

mission9_jacklin5/Pages/Shop.cshtml
@page
@model mission9_jacklin5.Pages.ShopModel
@{
}

<body class="bg-dark text-white">
    <h2>Your cart</h2>

    <table class="table bg-light table-bordered table-striped">         @*View for what we want to show in our cart*@

        <thead>
            <tr>
                <th>Book</th>
                <th>Quantity</th>
                <th>Cost</th>
                <th>Subtotal</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var i in Model.cart.Items)
            {
                <tr>
                    <td>@i.Book.Title</td>                  @*Information found on each book*@
                    <td>@i.Quantity</td>
                    <td>@(i.Book.Price.ToString("c"))</td>
                    <td>@(i.Quantity * i.Book.Price)</td>

                    <td class="text-center">
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="bookId" value="@i.Book.BookId" />        @*Need to identify what book we are deleting*@
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />  @*Send us back to where we came from*@
                            <button type="submit" class="btn btn-sm btn-dark">Remove</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>

        <tfoot>
            <tr>
                <td colspan="3">Total:</td>
                <td>@Model.cart.CalculateTotal().ToString("c")</td>         @*"c" makes it look like a currency*@
            </tr>
        </tfoot>


    </table>

    <div>
        <a class="btn btn-outline-danger" href="@Model.ReturnUrl">Continue Shopping</a>     @*Way for them to return where they were shopping*@
        <a class="btn btn-outline-danger" asp-action="Checkout" asp-controller="Payment">Checkout</a>
    </div>
</body>

mission9_jacklin5/Pages/_ShopLayout.cshtml
<!DOCTYPE html>
<link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
<html>
<head>
    <meta name="viewport" content="width=device-width" />       @*Shared Layout for cart page*@
    <title>@ViewBag.Title</title>
</head>
<body>

    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">The New Amazon Bookstore</span>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>