mission9_jacklin5/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission9_jacklin5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission9_jacklin5.Components
{
    public class CartSummaryViewComponent: ViewComponent        //Use this to create a cart image on our index page
    {
            private Cart cart;
            public CartSummaryViewComponent(Cart cartService)
            {
                cart = cartService;
            }
            public IViewComponentResult Invoke()
            {
                return View(cart);
            }
    }
}

mission9_jacklin5/Components/TypesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using mission9_jacklin5.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace mission9_jacklin5.Components
{
    public class TypesViewComponent : ViewComponent             //Consolidates information for us to use later
    {
        private IBookstoreRepository repo { get; set; }

        public TypesViewComponent(IBookstoreRepository temp)
        {
            repo = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["bookCategory"];       //Lists all the categories of books

            var types = repo.Books          //Uses Books to order the list of books that are found on the website
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x);

            return View(types);
        }
    }
}

mission9_jacklin5/Views/Shared/BookSummary.cshtml
@{
}
@model Book

    <body class="bg-dark">
        <div class="card card-outline-primary m-1 p-1">
            <div class="bg-faded p-1">
                <h4>
                    @Model.Title
                    <span class="badge badge-pill badge-primary bg-dark" style="float:right">
                        <small>@Model.Price.ToString("c")</small>       @*Puts praice for user to see in the upper right corner*@
                    </span>
                </h4>
            </div>
            <div class="card-text p-1">@Model.Category</div>


            <ul>
                <li>Author: @Model.Author</li>
                <li>Publisher: @Model.Publisher</li>            @*Lists information for each page, pulls from our queryable model*@
                <li>ISBN: @Model.ISBN</li>
                <li>Classification: @Model.Classification</li>
                <li>PageCount: @Model.PageCount</li>
                <li>Price: $@Model.Price</li>
            </ul>

            <form method="post" asp-page="/Shop">

                <input type="hidden" asp-for="@Model.BookId" />
                <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

                <span class="card-text">
                    <button type="submit" class="btn btn-danger btn-sm float-end">Purchase</button>         @*Sends user to cart page*@
                </span>
            </form>
        </div>
    </body>

    @*<div page-blah="@Model.PageInfo" page-action="Index"></div>*@    

mission9_jacklin5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>                               @*Default page for looks we want shared across pages*@
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">           @*Adds shopping cart image for us*@
            <div class="row">
                <div class="col navbar-brand">The New Amazon Bookstore</div>
                <div class="col-6 text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    @*<div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">The New Amazon Bookstore</span>
    </div>*@
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:types></vc:types>
        </div>
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>